### ISSUE TITLE
Code Homepage HTML

### ISSUE THREAD

**Issue by saimoh03** [saimoh03/html-css-assignment#10]
### Task 6: Code Homepage HTML
**Description**: Develop the HTML structure for the homepage.
- **Size**: Extra Large
- **Start Date**: 2024-11-20
- **Target Date**: 2024-12-03
- **Work Type**: HTML

**Checklist**:
- [x] Create header section
- [x] Add main content
- [x] Implement footer structure
