### ISSUE TITLE
Develop Footer Section

### ISSUE THREAD

**Issue by saimoh03** [saimoh03/html-css-assignment#13]
### Task  8: Develop Footer Section
**Description**: Code and style the footer.
- **Size**: Small
- **Start Date**: 2024-11-30
- **Target Date**: 2024-12-02
- **Work Type**: HTML, CSS

**Checklist**:
- [x] Code footer structure
- [x] Style footer elements
- [x] Add contact information
