### ISSUE TITLE
Create and Style Navigation Bar

### ISSUE THREAD

**Issue by saimoh03** [saimoh03/html-css-assignment#14]
### Task 9: Create and Style Navigation Bar
**Description**: Code and style the navigation bar.
- **Size**: Small
- **Start Date**: 2024-11-30
- **Target Date**: 2024-12-03
- **Work Type**: HTML, CSS

**Checklist**:
- [x] Implement navigation structure
- [x] Add links to main sections
- [x] Style links and hover effects
