### ISSUE TITLE
Project Reflection and Reporting

### ISSUE THREAD

**Issue by saimoh03** [saimoh03/html-css-assignment#24]
### Task 19: Project Reflection
**Description**: Write a project reflection and submit it.
- **Size**: Extra Small
- **Start Date**: 2024-12-07
- **Target Date**: 2024-12-07
- **Work Type**: Documentation

**Checklist**:
- [x] Reflect on project process
- [x] Identify key learnings
- [x] Write the SP1 CA Reflection Report
