### ISSUE TITLE
Create Wireframes

### ISSUE THREAD

**Issue by saimoh03** [saimoh03/html-css-assignment#8]
### Task  3: Create Wireframes both for Desktop and Mobile
**Description**: Design basic wireframes for key pages.
- **Size**: Large
- **Start Date**: 2024-11-20
- **Target Date**: 2024-11-21
- **Work Type**: Design

**Checklist**:
- [x] Create homepage wireframe
- [x] Create inner page wireframes
- [x] Review and finalize wireframes
- [x] Make sure both Screen and Mobile wireframes correspond to each
