### ISSUE TITLE
Set Up Project Structure

### ISSUE THREAD

**Issue by saimoh03** [saimoh03/html-css-assignment#9]
### Task 5: Set Up Project Structure 
**Description**: Initialize Figma Desktop and Mobile, HTML, CSS, and JavaScript files.
- **Size**: Small
- **Start Date**: 2024-11-20
- **Target Date**: 2024-11-22
- **Work Type**: Development

**Checklist**:
- [x] Plan the files to be used and check their size, and priorities. 
- [x] Set up file structure
- [x] Create Figma files
- [x] Create base HTML, CSS, JS files
- [x] Link files correctly
